import { Button, VerticalBox, HorizontalBox, ProgressIndicator, TextEdit, CheckBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Media Transcriber";
    icon: @image-url("icon.jpg");
    width: 750px;
    height: 600px;
    
    in property <string> text_with_timestamps: "Awaiting transcription...";
    in property <string> text_without_timestamps: "Awaiting transcription...";
    in-out property <bool> show_timestamps: true;
    
    in property <float> progress: 0.0;
    in property <bool> is_processing: false;
    
    callback select_file();
    callback start_transcription();
    callback copy_to_clipboard(string);
    callback save_to_file(string);

    VerticalBox {
        padding: 15px;
        spacing: 15px;
        
        Button {
            text: "Select Video File";
            clicked => { root.select_file(); }
            enabled: !root.is_processing;
        }
        
        Button {
            text: "Start Transcription";
            clicked => { root.start_transcription(); }
            enabled: !root.is_processing;
        }
        
        ProgressIndicator {
            progress: root.progress;
            indeterminate: root.is_processing && root.progress == 0.0;
        }
        
        TextEdit {
            text: root.show_timestamps ? root.text_with_timestamps : root.text_without_timestamps;
            read-only: true;
        }
        
        HorizontalBox {
            alignment: space-between;
            padding: 0px;
            
            CheckBox {
                text: "Show Timestamps";
                checked <=> root.show_timestamps;
            }
            
            HorizontalBox {
                spacing: 10px;
                padding: 0px;
                alignment: end;
                Button {
                    text: "📋 Copy to Clipboard";
                    clicked => { root.copy_to_clipboard(root.show_timestamps ? root.text_with_timestamps : root.text_without_timestamps); }
                }
                Button {
                    text: "💾 Save to File";
                    clicked => { root.save_to_file(root.show_timestamps ? root.text_with_timestamps : root.text_without_timestamps); }
                }
            }
        }
    }
}
